ci/.gitignore
ci/README.md
ci/credentials.yml.tpl
ci/main.tf
ci/pipeline-develop.yml
ci/tasks/build-candidate.sh
ci/tasks/build-candidate.yml
ci/tasks/utils.sh
config/final.yml

This change adds a simple Concourse pipeline that creates a BOSH release and its SHA1 and uploads them both to Google Cloud Storage. The accompanying README documents setting up the required infrastructure with Terraform.

ci: Initial support for building a dev BOSH release

---

README.md

This should demonstrate to an operator what IAM roles need added when using this release. 
This shouldn't be required for a new instance once [this PR](https://github.com/cloudfoundry-incubator/bosh-google-cpi-release/pull/90) is merged.

Add access control documentation for the operator

---

config/final.yml

`config/final.yml` should be structured as:
```
blobstore:
provider: s3
options:
bucket_name: your-bucket-name
host: storage.googleapis.com
use_ssl: true
```

GCS can be used as a blobstore for uploading blobs

---

README.md
jobs/stackdriver-agent/templates/stackdriver_collectd_ctl
jobs/stackdriver-agent/templates/stackdriver_extractor_ctl

- Added documentation on how to set the stackdriver-agent-key metadata field. This can't be autodetected like other various compute properties.
- Added '|| true' to the metadata queries in the stackdriver start scripts. Without this a failure to get the metadata is a silent failure in the script. 
[#131196105](https://www.pivotaltracker.com/story/show/131196105)

Enable StackDriver Agent deployment

---

src/stackdriver-nozzle/nozzle/nozzle.go
src/stackdriver-nozzle/nozzle/nozzle_test.go

Post container metrics as metrics instead of logs. We would like some feedback on how we handle the async error channel for the container metrics.

Post container metrics

---

src/stackdriver-nozzle/heartbeat/heartbeat_test.go
src/stackdriver-nozzle/mocks/logger.go
src/stackdriver-nozzle/mocks/serializer.go
src/stackdriver-nozzle/nozzle/nozzle.go
src/stackdriver-nozzle/nozzle/nozzle_test.go
src/stackdriver-nozzle/serializer/serializer.go
src/stackdriver-nozzle/serializer/serializer_test.go

Counter events will now be sent to stack driver as metrics instead of logs.
Note that we are using the "total" value of the metric instead of the "delta". 
This might need to be revisited at a later point. I think total is fine for MVP.

Implement counter events as a metric instead of a log event

---

ci/credentials.yml.tpl
ci/pipeline.yml
ci/tasks/deploy-candidate.sh
ci/tasks/deploy-candidate.yml
ci/tasks/unit-tests.yml

This change adds a Concourse task to upload the latest nozzle release and re-deploy the CloudFoundry deployment that uses it.

Concourse uploads and deploys nozzle release

---

jobs/stackdriver-nozzle/spec
jobs/stackdriver-nozzle/templates/stackdriver-nozzle-ctl.erb
packages/common/packaging
packages/common/spec

These commits include the dependency for the `pid_guard` function. They also run the `stackdriver-nozzle` process as the default user. Otherwise, the `vcap` user is unable to create the boltdb file required to run.

Fix stackdriver-nozzle job

---

ci/credentials.yml.tpl
ci/docker/Dockerfile
ci/pipeline.yml
ci/tasks/build-candidate.yml
ci/tasks/deploy-candidate.sh
ci/tasks/deploy-candidate.yml
ci/tasks/unit-tests.yml

This change uses an SSH tunnel to communicate with a BOSH director via its private IP address.

Use an SSH tunnel to connect to BOSH director

---

src/stackdriver-nozzle/nozzle/label_maker.go
src/stackdriver-nozzle/nozzle/label_maker_test.go

We will no longer send IP and deployment as labels since it would cause some metrics to go over 10 labels. We are always removing them because otherwise there might be a case where we are not sending the same number of labels as the existing descriptor (if we are not resolving the app metadata for example).

Remove ip and deployment from labels

---

src/stackdriver-nozzle/mocks/metric_adapter.go
src/stackdriver-nozzle/stackdriver/metric_adapter.go
src/stackdriver-nozzle/stackdriver/metric_adapter_test.go
src/stackdriver-nozzle/stackdriver/metrics_buffer.go
src/stackdriver-nozzle/stackdriver/metrics_buffer_test.go

We are doing this instead of a worker pool since it is the only call that was not yet async.

Made the posting metrics call async at the buffer-level

---

src/stackdriver-nozzle/main.go
src/stackdriver-nozzle/stackdriver/metric_adapter.go
src/stackdriver-nozzle/stackdriver/metric_adapter_test.go

We used to fatal if the metric adapter encountered an error during initialization (pre-heating the cache). This meant that we panicked as soon as we tried to connect to the metric adapter due to our max quota reached error.

Do not panic if the metric adapter fails to prep the cache of existing metric descriptors

---

src/stackdriver-nozzle/filter/filter.go
src/stackdriver-nozzle/filter/filter_test.go
src/stackdriver-nozzle/heartbeat/heartbeat.go
src/stackdriver-nozzle/heartbeat/heartbeater.go
src/stackdriver-nozzle/heartbeat/heartbeater_test.go
src/stackdriver-nozzle/main.go
src/stackdriver-nozzle/mocks/heartbeater.go
src/stackdriver-nozzle/nozzle/nozzle.go
src/stackdriver-nozzle/nozzle/nozzle_test.go
src/stackdriver-nozzle/scripts/metrics_per_batch.rb
src/stackdriver-nozzle/scripts/metrics_stats.rb
src/stackdriver-nozzle/stackdriver/log_adapter.go
src/stackdriver-nozzle/stackdriver/metric_adapter.go
src/stackdriver-nozzle/stackdriver/metric_adapter_test.go
src/stackdriver-nozzle/stackdriver/metrics_buffer.go
src/stackdriver-nozzle/stackdriver/metrics_buffer_test.go

The heartbeat now records:
* # Metric requests
* # Metric Timeseries
* # Logs
* # Stackdriver Metric Client Errors
Instead of sending a duplicate metric individually, we will now send the current buffer of metrics and start a new one with the duplicate. 
Added a script to get statistic on our heartbeat.

Record more info in Heartbeat + Improved Efficiency of Batching

---

src/stackdriver-nozzle/nozzle/log_sink.go
src/stackdriver-nozzle/nozzle/log_sink_test.go
src/stackdriver-nozzle/stackdriver/log_adapter.go

This change resolves the severity from LogMessage.MessageType. It also duplicates the message payload in a spot where Stackdriver expects it. This preserves the event object structure while making the console way more readable.

Add Severity for LogMessages and better Message Payload

---

jobs/google-fluentd/templates/google-fluentd.conf
jobs/google-fluentd/templates/vcap.conf

This PR extends the behaviour of the google-fluentd configuration such that when it forwards the contents of a log from /var/vcap/sys/log/*/*.log it includes metadata so that the log source can be identified.
Specifically, the following metadata attributes are added
- metadata.labels.deployment
- metadata.labels.job
- metadata.labels.index
- metadata.labels.log_path
This enables searching for specific component logs in StackDriver Logging using a search query like:
```
log="vcap" AND metadata.labels.deployment="cf-c201d9fbf59670f9d707" AND metadata.labels.job="uaa" AND metadata.labels.index="0" 
```

Add metadata.labels to indentify the source of the log line

---

jobs/google-fluentd/templates/google-fluentd.conf

Enables the plugin introduced by e2c845b
Fixes #64 
Validation
- Deploy dev release, verified logs are still getting into Stackdriver Logging

Activate exception detection on google-fluentd

---

src/stackdriver-nozzle/config/config.go
src/stackdriver-nozzle/main.go
src/stackdriver-nozzle/mocks/metrics_buffer.go
src/stackdriver-nozzle/stackdriver/auto_culled_metrics_buffer.go
src/stackdriver-nozzle/stackdriver/auto_culled_metrics_buffer_test.go
src/stackdriver-nozzle/stackdriver/metric_adapter.go
src/stackdriver-nozzle/stackdriver/metric_client.go
src/stackdriver-nozzle/stackdriver/metrics_buffer.go
src/stackdriver-nozzle/stackdriver/metrics_buffer_test.go
src/stackdriver-nozzle/vendor/github.com/mitchellh/hashstructure/LICENSE
src/stackdriver-nozzle/vendor/github.com/mitchellh/hashstructure/README.md
src/stackdriver-nozzle/vendor/github.com/mitchellh/hashstructure/hashstructure.go
src/stackdriver-nozzle/vendor/github.com/mitchellh/hashstructure/include.go
src/stackdriver-nozzle/vendor/vendor.json

> WIP: needs more unit tests
This change allows metrics to be buffered and drained after a duration.
A duplicate metric (i.e., metric name and labels are identical to an
existing buffered metric) overwrites the existing metric it matches.
Addresses #62

WIP: Timeseries timer buffer

---

src/stackdriver-nozzle/nozzle/log_sink.go
src/stackdriver-nozzle/nozzle/log_sink_test.go

Verified the output now looks like:
```
httpStartStop: {
contentLength: 91
uri: "https://api.cf.jrjohnson-kubo.cloudnativeapp.com/v2/syslog_drain_urls"
remoteAddress: "10.138.3.17:46394"
method: "GET"
startTimestamp: 1487098222367823000
userAgent: "Go-http-client/1.1"
>   requestId: "64ba1ea5-17ec-4b6d-7825-17a2536eaab8"
statusCode: 500
stopTimestamp: 1487098222378248400
peerType: "Server"
}
```
Fixes #60
I used the `applicationId` UUID for the requestId because it's a known example of how to go from events.UUID to a string.  Updated the applicationId to a new UUID to keep it unique.

format UUID into string for HttpStartStop.RequestId

---

README.md

Clean up this section a bit and mention the credentials job.
Merging this directly to master as it's a doc update and not dependent on anything in develop. 
Fixes #82

Add monitoring roles to requirements

---

jobs/credentials/templates/pre-start.erb
jobs/stackdriver-nozzle/spec
jobs/stackdriver-nozzle/templates/application_default_credentials.json.erb
jobs/stackdriver-nozzle/templates/stackdriver-nozzle-ctl.erb
tile.yml.erb

Credentials now handled by the `stackdriver-nozzle` job.

PR: Remove credentials job from nozzle tile

---

examples/cf-stackdriver-example/main.go

The datastore was incorrectly created in scope of the list handler while
the other methods expect the package variable to be set.
Added the connect step to main and a more helpful error message for when
it doesn't work.

examples/cf-stackdriver-example: Datastore not shared between requests

---

src/stackdriver-nozzle/nozzle/metric_sink.go
src/stackdriver-nozzle/nozzle/metric_sink_test.go

Reverts cloudfoundry-community/stackdriver-tools#102
This exceeds Stackdriver's limit of 10 labels per metric

Revert "nozzle/metric_sink: emit instanceIndex as a label"

---

ci/docker/Dockerfile
config/blobs.yml
config/final.yml
packages/golang/packaging
packages/golang/spec

- remove unused go1.6
- replace go1.7 with go1.9
- update dockerfile, needs built: related #108
- had to move the blobstore due to access, related: #109

bosh-release: update to go1.9

---

src/stackdriver-nozzle/app/builder.go
src/stackdriver-nozzle/app/runner.go
src/stackdriver-nozzle/cloudfoundry/firehose.go
src/stackdriver-nozzle/heartbeat/heartbeater.go
src/stackdriver-nozzle/heartbeat/heartbeater_test.go
src/stackdriver-nozzle/heartbeat/logger_handler.go
src/stackdriver-nozzle/heartbeat/metric_handler.go
src/stackdriver-nozzle/messages/metric.go
src/stackdriver-nozzle/metrics_pipeline/auto_culled_metrics_buffer.go
src/stackdriver-nozzle/metrics_pipeline/auto_culled_metrics_buffer_test.go
src/stackdriver-nozzle/metrics_pipeline/router.go
src/stackdriver-nozzle/metrics_pipeline/router_test.go
src/stackdriver-nozzle/mocks/metric_adapter.go
src/stackdriver-nozzle/mocks/metrics_buffer.go
src/stackdriver-nozzle/nozzle/metric_sink.go
src/stackdriver-nozzle/nozzle/metric_sink_test.go
src/stackdriver-nozzle/nozzle/nozzle.go
src/stackdriver-nozzle/stackdriver/log_adapter.go
src/stackdriver-nozzle/stackdriver/metric_adapter.go
src/stackdriver-nozzle/stackdriver/metric_adapter_test.go
src/stackdriver-nozzle/vendor/code.cloudfoundry.org/diodes/LICENSE
src/stackdriver-nozzle/vendor/code.cloudfoundry.org/diodes/NOTICE
src/stackdriver-nozzle/vendor/code.cloudfoundry.org/diodes/README.md
src/stackdriver-nozzle/vendor/code.cloudfoundry.org/diodes/many_to_one.go
src/stackdriver-nozzle/vendor/code.cloudfoundry.org/diodes/one_to_one.go
src/stackdriver-nozzle/vendor/code.cloudfoundry.org/diodes/poller.go
src/stackdriver-nozzle/vendor/code.cloudfoundry.org/diodes/waiter.go
src/stackdriver-nozzle/vendor/vendor.json

Changes for operators (from `develop`):
- Logs will once again appear in the `Global` resource. A dependency update caused the logs to show up under GCE VMs.
- Metric events emitted to Stackdriver Logging (eg `ContainerMetric`) are now bundled in a single log entry instead of a log entry per data point. Example:
```
{
insertId:  "1flxwd4g2lwzl4c"  
jsonPayload: {
Metrics: [
0: {
EventTime:  "2017-10-11T08:33:25.781744816-07:00"     
Name:  "dropped.delta"     
Unit:  ""     
Value:  0     
}
1: {
EventTime:  "2017-10-11T08:33:25.781744816-07:00"     
Name:  "dropped.total"     
Unit:  ""     
Value:  0     
}
]
}
labels: {
eventType:  "CounterEvent"   
index:  "53b88475-8f46-4350-977b-2ab027e011e6"   
job:  "router"   
origin:  "loggregator.metron"   
}
logName:  "<redacted>/logs/cf_logs" …
```

Nozzle Reliability Improvements

---

src/stackdriver-nozzle/mocks/metric_client.go
src/stackdriver-nozzle/stackdriver/metric_adapter.go
src/stackdriver-nozzle/stackdriver/metric_adapter_test.go

Once there is more than a single nozzle writing we expect these errors
and should not count them in the same way. These occur when more than a
single nozzle is writing to stackdriver. If nozzle A writes a metric at
time T2 and nozzle B writes a netric at time T1 then nozzle B will get
an error that it is writing out of order.
- Emit `metrics.errors.out_of_order` and `metrics.errors.unknown` to
help operators understand this.
- Don't output the entire metric request for these errors. That detail
is useful for tracking down specific errors and this error is tracked
down.
Fixes #98

stackdriver/metric: measure out of order write errors

---

tile.yml.erb

Commit 5000810f allowed for side by side installation of master/develop
nozzles but it did not specify a unique subscription_id. The nozzle
identifies itself to firehose with this value and firehose will shard
across a set of nozzles with the same subscription_id.
- Specify a unique subscription_id as part of the tile configuration.
On released tiles this will be unchanged: stackdriver-nozzle
On develop tiles this will be changed: stackdriver-nozzle-develop
Fixes #119

tile: side-by-side execution of master/develop

---

tile.yml.erb

- pcf 2.0 requirement (updates #125)
- no other jobs reference the nozzle so should have no impact on users

tile: use dynamic_ip for nozzle job

---

src/stackdriver-nozzle/app/builder.go
src/stackdriver-nozzle/app/runner.go
src/stackdriver-nozzle/heartbeat/metric_handler.go
src/stackdriver-nozzle/main.go
src/stackdriver-nozzle/nozzle/nozzle.go

- A firehose error would not be drained if the nozzle could not write to stackdriver. Repro: Run the nozzle, unplug your ethernet cable, wait, plug it back in, the errors from firehose disconnecting finally show up. This was due to heartbeater.Increment blocking.
- Ignore empty error messages from Firehose and instrument a metric to track them. This is a bandaid for observed behavior and may be removed if it proves unneeded.
- Write errors to stderr to help understanding of the logs.
- Small optimization to the heartbeat/metric_handler to not block Increment during Flush
- Turn Errors into Fatal calls during app construction to prevent partially valid state. This wasn't ever observed but it is the right thing to do.

Improved Firehose Error Handling

---

ci/pipeline-develop.yml
ci/pipeline.yml
ci/tasks/build-candidate.sh
ci/tasks/build-tile.sh
ci/tasks/build-tile.yml
ci/tasks/deploy-candidate.sh
ci/tasks/deploy-candidate.yml
ci/tasks/promote-candidate.sh
ci/tasks/promote-candidate.yml
tile.yml.erb

- output a pivotal.sha256 for tile builds
- change the sha1 to sha256 for bosh release
- (semi related) use the local file system to expose the bosh release to the tile builder instead of the GCS URL

CI: use sha256 across the board

---

ci/pipeline-develop.yml
ci/pipeline.yml

message:
DEPRECATION WARNING:
- jobs.build-candidate.plan[2].task.make-semver-public specifies both
`file` and `config` in a task step
- jobs.deploy-candidate.plan[1].task.deploy-candidate specifies
both `file` and `config` in a task step
related: concourse/concourse#286

ci: squash deprecation warning

---

src/stackdriver-nozzle/stackdriver/metric_adapter.go
src/stackdriver-nozzle/stackdriver/metric_adapter_test.go

This is restoring what I believe is previous behavior to send requests to Stackdriver Monitoring in batches. I believe the work to group a set of metrics from a single firehose event introduced this regression, but I'm not completely sure. 
This change should significantly (100x) reduce the RPS to Stackdriver Monitoring.
- Change `PostMetricEvents` to collect all provided metrics into a single `TimeSeriesRequest`
- Move out error telemetry to a specialized error object
- Don't fail the entire post on a single error

Respect metric batches

---

src/stackdriver-nozzle/metrics_pipeline/router.go

This will ensure that SD API errors reach stackdriver nozzle log file.

Propagate PostMetricEvents() errors

---

src/stackdriver-nozzle/messages/metric.go
src/stackdriver-nozzle/metrics_pipeline/auto_culled_metrics_buffer_test.go

This will make sure that each set of metrics is deduplicated ("culled")
independently even if they share the same label values.

Include metric names while deduplicating values in the buffer.

---

jobs/stackdriver-nozzle/spec
jobs/stackdriver-nozzle/templates/stackdriver-nozzle-ctl.erb
src/stackdriver-nozzle/README.md
src/stackdriver-nozzle/app/builder.go
src/stackdriver-nozzle/config/config.go
tile.yml.erb

Also, rename `batch_count` and `batch_duration` internally to make it more obvious that they only apply to Stackdriver logging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/138)

Make nozzle buffer size configurable via manifest

---

src/stackdriver-nozzle/nozzle/metric_sink.go
src/stackdriver-nozzle/nozzle/metric_sink_test.go

[Pivotal's docs][1] use the origin to differentiate between metrics that
have the same name, explicitly prepending it to the metric name. The
DataDog nozzle does the same thing. Consistency with these is valuable,
though this does introduce a change in metric naming that is not
backwards-compatible.
Example name changes, first the "now matches the docs, but whatever":
*   AuctioneerTaskAuctionsFailed → auctioneer.AuctioneerTaskAuctionsFailed
*   LRPsExtra → bbs.LRPsExtra
Then the "wow, disambiguation is helpful!":
*   RequestLatency → bbs.RequestLatency
*   latency → gorouter.latency
*   Latency → etcd.Latency
*   requests.completed → cc.requests.completed
*   total_requests → gorouter.total_requests
*   ReceivingRequestRate → etcd.ReceivingRequestRate
Then the "maybe we don't want to do …

Prepend event origin to all generated metric names.

---

src/stackdriver-nozzle/metrics_pipeline/auto_culled_metrics_buffer.go
src/stackdriver-nozzle/metrics_pipeline/auto_culled_metrics_buffer_test.go

The firehose does not guarantee in-order message delivery,
so it is possible for the nozzle to receive older metrics with
the same Hash() after newer ones.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/141)

Cull metrics based on event timestamp.

---

src/stackdriver-nozzle/mocks/label_maker.go
src/stackdriver-nozzle/nozzle/label_maker.go
src/stackdriver-nozzle/nozzle/label_maker_test.go
src/stackdriver-nozzle/nozzle/log_sink.go
src/stackdriver-nozzle/nozzle/log_sink_test.go
src/stackdriver-nozzle/nozzle/metric_sink.go

Stackdriver (SD) imposes a limit of 10 labels per custom metric. Simply copying event metadata into SD labels results in some metrics hitting that limit.
To address this, drop eventType and the org, space, and application UUIDs from metric labels completely. Create an "applicationPath" label that concatenates together the org, space and application name.
Keep the VM and application index labels separate so that higher level aggregations of the same metric data can be created.
Distinguish between the labels applied to log messages and the labels applied to metrics, because distinguishing logs by origin and event type is useful and there doesn't appear to be a similar label limit for SD logging.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

Reduce number and increase consistency of metric/log labels.

---

jobs/stackdriver-nozzle/spec
jobs/stackdriver-nozzle/templates/stackdriver-nozzle-ctl.erb
src/stackdriver-nozzle/README.md
src/stackdriver-nozzle/app/builder.go
src/stackdriver-nozzle/app/runner.go
src/stackdriver-nozzle/config/config.go
src/stackdriver-nozzle/heartbeat/heartbeater.go
src/stackdriver-nozzle/heartbeat/heartbeater_test.go
src/stackdriver-nozzle/heartbeat/logger_handler.go
src/stackdriver-nozzle/heartbeat/metric_handler.go
src/stackdriver-nozzle/metrics_pipeline/auto_culled_metrics_buffer.go
src/stackdriver-nozzle/metrics_pipeline/auto_culled_metrics_buffer_test.go
src/stackdriver-nozzle/metrics_pipeline/metrics_pipeline_suite_test.go
src/stackdriver-nozzle/metrics_pipeline/router.go
src/stackdriver-nozzle/metrics_pipeline/router_test.go
src/stackdriver-nozzle/mocks/metric_adapter.go
src/stackdriver-nozzle/mocks/metric_client.go
src/stackdriver-nozzle/mocks/metrics_buffer.go
src/stackdriver-nozzle/mocks/sink.go
src/stackdriver-nozzle/nozzle/filter_sink.go
src/stackdriver-nozzle/nozzle/filter_sink_test.go
src/stackdriver-nozzle/nozzle/log_sink.go
src/stackdriver-nozzle/nozzle/metric_sink.go
src/stackdriver-nozzle/nozzle/metric_sink_test.go
src/stackdriver-nozzle/nozzle/nozzle.go
src/stackdriver-nozzle/nozzle/nozzle_test.go
src/stackdriver-nozzle/nozzle/sink.go
src/stackdriver-nozzle/stackdriver/metric_adapter.go
src/stackdriver-nozzle/stackdriver/metric_adapter_test.go
tile.yml.erb

Move batching down the pipeline so we can do it at the `TimeSeries` level. The `AutoCullingMetricsBuffer` can't accurately batch because it deals in `MetricEvent` which may result in multiple `TimeSeries`. Plus it's not the `AutoCullingMetricsBatchingBuffer` is it? 
This change moves out the Stackdriver implementation behavior of sending 200 or less time series per request into the `MetricAdapter`
Fixes #137
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/143)

Move batching to stackdriver.MetricAdapter

---

jobs/stackdriver-nozzle/spec
jobs/stackdriver-nozzle/templates/stackdriver-nozzle-ctl.erb
src/stackdriver-nozzle/README.md
src/stackdriver-nozzle/app/builder.go
src/stackdriver-nozzle/config/config.go
src/stackdriver-nozzle/nozzle/label_maker.go
src/stackdriver-nozzle/nozzle/label_maker_test.go
src/stackdriver-nozzle/nozzle/metric_sink.go
src/stackdriver-nozzle/nozzle/metric_sink_test.go
tile.yml.erb

The nozzle currently places all the metrics it derives from firehose
data in the root of Stackdriver's custom metric namespace. This means
there's a relatively large chance that these names could collide with
others that were not created by the nozzle. To mitigate this, a config
option "metric_path_prefix" (that defaults to "firehose") is added.
After this commit, Stackdriver metric names will be of the form:
custom.googleapis.com/PREFIX/origin.Name
custom.googleapis.com/firehose/gorouter.total_requests
Running multiple PCF instances in the same GCP project will result in
metrics from all instances being confused with each other. Since the
nozzle runs on BOSH, another config option "bosh_director_name" (that
defaults to "cf") has been added. This sets the value of a static
"director" …

 Config options for metric prefix and director name.

---

src/stackdriver-nozzle/nozzle/metric_sink.go
src/stackdriver-nozzle/nozzle/metric_sink_test.go

This isn't a metric, it's a label as repoted by #100. We now properly
emit it as a label as of #136.
This change is simply cleanup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/145)

nozzle/metric_sink: remove instanceIndex metric

---

src/stackdriver-nozzle/cmd/clear-metrics-descriptors.go

the stackdriver API uses the standardized iterator.Done instead of a
monitoring specific .Done
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/146)

cmd/clear-metric-descriptors: fix for api change

---

src/stackdriver-nozzle/mocks/logger.go
src/stackdriver-nozzle/nozzle/nozzle.go
src/stackdriver-nozzle/nozzle/nozzle_test.go

If we reach the max number of connection retries we need to do something
besides spin. Log them as fatal errors which will cause a crash.
Fixes #149
/cc @knyar @fluffle
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/151)

nozzle: crash on MaxRetriesReached

---

jobs/stackdriver-nozzle/spec
jobs/stackdriver-nozzle/templates/stackdriver-nozzle-ctl.erb
src/stackdriver-nozzle/app/runner.go
src/stackdriver-nozzle/config/config.go
tile.yml.erb

- Expose `NOZZLE_DEBUG` setting to allow for pprof access on the hosted
nozzle (http://<VM>:6060/debug/pprof/). This also enables Stackdriver Error reporting for crashes. Fixes #114
- Expose Logging buffer duration/size settings and update default to a more reasonable value
- Add Labels for recently added options in the tile for better presentation. At some point we'll want to separate these settings into logical pages now that the options are getting long.
/cc @knyar @fluffle
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/147)

stackdriver-nozzle/tile: debugging options, logging configuration

---

config/blobs.yml
config/final.yml

Native GCS support for developers using the public bucket is blocked on
cloudfoundry/bosh#343 being merged.
This reverts commit f0a39ee3e097afc8c8d9772b430ab4842d372623.
Signed-off-by: Jeff Johnson <jrjohnson@google.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/154)

Revert "ci: use gcs blobstore"

---

src/stackdriver-nozzle/messages/metric.go
src/stackdriver-nozzle/metrics_pipeline/auto_culled_metrics_buffer.go
src/stackdriver-nozzle/metrics_pipeline/auto_culled_metrics_buffer_test.go
src/stackdriver-nozzle/metrics_pipeline/router.go
src/stackdriver-nozzle/metrics_pipeline/router_test.go
src/stackdriver-nozzle/mocks/metric_adapter.go
src/stackdriver-nozzle/mocks/metrics_buffer.go
src/stackdriver-nozzle/nozzle/metric_sink.go
src/stackdriver-nozzle/nozzle/metric_sink_test.go
src/stackdriver-nozzle/stackdriver/metric_adapter.go
src/stackdriver-nozzle/stackdriver/metric_adapter_test.go

`MetricEvent` seems like an artifact of Firehose data model (`Envelope` being separate from the metric itself) which is quite unusual and difficult to reason about. I would like to propose merging `Metric` and `MetricEvent` structs.
I've realized that `router.PostMetrics` also sends metric events to Stackdriver logging, and this changes the payload. Please let me know if you think it's a concern.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/156)

Merge Metric and MetricEvent (#142)

---

src/stackdriver-nozzle/app/builder.go
src/stackdriver-nozzle/config/config.go
src/stackdriver-nozzle/mocks/label_maker.go
src/stackdriver-nozzle/nozzle/label_maker.go
src/stackdriver-nozzle/nozzle/label_maker_test.go
src/stackdriver-nozzle/nozzle/metric_sink.go
src/stackdriver-nozzle/nozzle/metric_sink_test.go

I've chosen to call these "runtime metrics" based on [the piece that generates them](https://github.com/cloudfoundry/dropsonde/blob/master/runtime_stats/runtime_stats.go).
Please let me know if you can come up with a better term :)
The regular expression is part of the config to avoid hard-coding it as a string elsewhere. I don't really expect anyone to override this, which is why it's not wired through to the manifest or tile.
I considered a comma-separated list of metric names instead of a regular expression, but it will be pretty long. Happy to do that if you think the performance difference matters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-too …

Deduplicate runtime metrics (fix #157)

---

src/stackdriver-nozzle/nozzle/nozzle.go

The Nozzle should delegate event routing decisions to the filter sink,
instead of having a second, hard-coded set of events that are metrics.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/163)

Send all events to both Nozzle sinks.

---

jobs/stackdriver-nozzle/spec
jobs/stackdriver-nozzle/templates/stackdriver-nozzle-ctl.erb
src/stackdriver-nozzle/app/builder.go
src/stackdriver-nozzle/config/config.go
src/stackdriver-nozzle/messages/metric.go
src/stackdriver-nozzle/nozzle/counter_tracker.go
src/stackdriver-nozzle/nozzle/counter_tracker_test.go
src/stackdriver-nozzle/nozzle/metric_sink.go
src/stackdriver-nozzle/nozzle/metric_sink_test.go
src/stackdriver-nozzle/stackdriver/metric_adapter.go
src/stackdriver-nozzle/stackdriver/metric_adapter_test.go

This adds a "counter tracker" which is used to maintain start time and a separate cumulative value for each counter metric, which need to be reported to Stackdriver.
As the result, each counter is properly exported as a cumulative Stackdriver metric instead of two gauge metrics (`.total` and `.delta`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/162)

Report CounterEvents as cumulative metrics to Stackdriver

---

src/stackdriver-nozzle/app/builder.go

After #163 there is no hard-coded filtering based on event type, and `firehose_events_to_stackdriver_logging` and `firehose_events_to_stackdriver_monitoring` actually determine which events should be sent to which sink.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/169)

Do not send log events to metric sink

---

src/stackdriver-spinner/cloudfoundry/emitter.go
src/stackdriver-spinner/cloudfoundry/emitter_test.go
src/stackdriver-spinner/main.go
src/stackdriver-spinner/session/session.go
src/stackdriver-spinner/session/session_test.go

We've added a stagger of 10ms between each emitted log message. This is to make the load generated more realistic. Also, the log format has been changed to JSON w/timestamps for easier grepping etc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/172)

Staggered logging and json log format

---

jobs/stackdriver-nozzle/templates/event_filters.json.erb

Use if_p instead of the misguided (by my CR comment) if p("..")
fixes #181
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/182)

event_filters.json: don't read property if it's not set

---

src/stackdriver-nozzle/stackdriver/metric_adapter.go
src/stackdriver-nozzle/stackdriver/metric_adapter_test.go
src/stackdriver-nozzle/stackdriver/metric_client.go
src/stackdriver-nozzle/stackdriver/telemetry_sink.go

- Increment counters in metric client instead of metric adapter.
- Log SD errors returned to telemetry sink.
This is what prompted @knyar's PR #180. I have taken the lazy way out with tests: I just deleted the ones testing metric increments instead of trying to figure out a neat way of mocking/faking the Stackdriver client. If you'd prefer that I reinstate them, I can probably do that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/183)

Instrument telemetry path for SD metrics.

---

jobs/stackdriver-nozzle/spec
jobs/stackdriver-nozzle/templates/stackdriver-nozzle-ctl.erb
src/stackdriver-nozzle/app/builder.go
src/stackdriver-nozzle/config/config.go
src/stackdriver-nozzle/messages/metric.go
src/stackdriver-nozzle/nozzle/httpstartstop_sink.go
src/stackdriver-nozzle/nozzle/httpstartstop_sink_test.go
src/stackdriver-nozzle/nozzle/label_maker.go
src/stackdriver-nozzle/nozzle/nozzle.go
src/stackdriver-nozzle/stackdriver/metric_client.go
src/stackdriver-nozzle/stackdriver/telemetry_sink.go
src/stackdriver-nozzle/stackdriver/telemetry_sink_test.go
src/stackdriver-nozzle/telemetry/counters.go
src/stackdriver-nozzle/telemetry/log_sink.go

This will create Stackdriver metrics to track the request rates and response codes of individual PCF apps from the gorouter's HttpStartStop events. It allows the creation of simple SLIs based on e.g. the ratio of 500s.
I intend to use this as a proof-of-concept for per-application SLOs. It's not clear that this functionality *should* be in the nozzle, though if we want proper counters and latency distributions then it kinda has to be. I would appreciate code reviews anyway if you're not too busy :-)
Please don't merge this until we're sure the nozzle is the right place for this code, instead of e.g. having the gorouter track and emit these metrics.
/cc @johnsonj @knyar
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Per-app HTTP metrics derived from HttpStartStop events.

---

README.md
ci/pipeline-develop.yml
ci/tasks/build-candidate.sh
ci/tasks/deploy-candidate.sh
ci/tasks/deploy-candidate.yml
manifests/cloud-config-gcp.yml
manifests/stackdriver-tools.yml

Updates example manifest to use take advantage of BOSH 2.0. The example manifest is also used in CI for validation. 
Fixes #125, #174
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/188)

Use bosh2 in CI, documentation 

---

config/final.yml

Use the GCS provider to fetch blobs. This does not require updates to the blobs because they have always been stored in this bucket.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/189)

Use native Google Cloud Storage for release blobs

---

src/stackdriver-nozzle/stackdriver/metric_adapter.go
src/stackdriver-nozzle/stackdriver/metric_adapter_test.go

It has the same value as `metrics.timeseries.count`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/191)

Remove reduntant metrics.firehose_events.emitted.count metric.

---

jobs/stackdriver-nozzle/spec
jobs/stackdriver-nozzle/templates/stackdriver-nozzle-ctl.erb
src/stackdriver-nozzle/app/builder.go
src/stackdriver-nozzle/config/config.go
src/stackdriver-nozzle/stackdriver/log_adapter.go
src/stackdriver-nozzle/vendor/cloud.google.com/go/LICENSE
src/stackdriver-nozzle/vendor/cloud.google.com/go/logging/doc.go
src/stackdriver-nozzle/vendor/cloud.google.com/go/logging/logging.go
src/stackdriver-nozzle/vendor/google.golang.org/api/support/bundler/bundler.go
src/stackdriver-nozzle/vendor/vendor.json
tile.yml.erb

Thanks to some great work by @jba we can now have multiple in-flight requests to Stackdriver. This should make Nozzle throughput much less susceptible to latency-induced drops.
This PR pulls in the vendor changes and adds a new config option so that the concurrency limit is tuneable (default: 16).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/193)

Concurrent in-flight requests to Stackdriver Logging

---

scripts/build-docker-env.sh
scripts/custom-tile

- Update bosh cli to resolve GCS bucket access issue.
- Make current timestamp part of the tile version, which will ensure
that the latest built tile has the highest version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/196)

Custom tiles: update bosh, make timestamp part of version (fix #195)

---

jobs/stackdriver-nozzle/spec
jobs/stackdriver-nozzle/templates/stackdriver-nozzle-ctl.erb
tile.yml.erb

Also, enable cumulative counters by default, which should work fine with
a single nozzle instance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/197)

Restrict nozzle to a single running instance (fix #190)

---

tile.yml.erb

Stackdriver Monitoring enforces a limit of 500 custom metrics per project.
Many of the metrics the nozzle automatically derives from the firehose are
not useful for understanding the performance of a PCF instance, and thus
wastefully consume a scarce resource. Pivotal's documentation describes
the set of firehose metrics that *are* useful, so the tile whitelists
these by default.
Note that installing the BOSH release directly into the director will
not set up this whitelisting.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/192)

Nozzle tile: selective whitelist of KPI/KCSI metrics.

---

docs/upgrading_2.0.md
src/stackdriver-nozzle/cmd/clear-metrics-descriptors.go
src/stackdriver-nozzle/docs/clear-metrics-descriptors.md

- Added usability improvements to the clear-metrics-descriptors script.
This adds a confirmation prompt, presence validation for the
GCP_PROJECT_ID, and cleaned up output.
- Add specific instructions for clearing out metrics descriptors. This
doc omits the need to use the develop branch. That's fine- if someone
does follow these steps today it will work.
- Add general 2.0 upgrade instructions with guidance on singleton
instance of the nozzle and the need for clear-metrics-descriptors.
updates #185 
/cc @knyar @fluffle
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/198)

clear-metrics-descriptors: docs and usability

---

src/stackdriver-nozzle/cloudfoundry/firehose.go

Decreasing the retry count, so that the nozzle fails faster when it can't possibly recover
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/207)

Decrease the retry count from the default 1000

---

jobs/stackdriver-agent/templates/collectd-gcm.conf.tmpl

The stackdriver agent job should utilize its own credentials file rather than depending on the nozzle to be running as well
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/206)

Stackdriver-agent credentials fix

---

src/stackdriver-nozzle/Makefile

The golint code moved from github.com/golang/lint/golint to goland.org/x/lint/golint
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/210)

update the golint dependency path

---

jobs/stackdriver-nozzle/spec
jobs/stackdriver-nozzle/templates/stackdriver-nozzle-ctl.erb
manifests/stackdriver-tools-bosh-lite.yml
manifests/stackdriver-tools.yml
scripts/build-custom-tile-docker.sh
scripts/custom-tile
tile.yml.erb

* Generate an x509 certificate for RLP's mutual TLS
* Derive the root Certificate Authority
* Add the BOSH DNS hostname for the Reverse Log Proxy as a default value
* Derive the API URL
I've tested this works with the large footprint. I'm currently working on testing this with the small footprint. However, I ran into issues with the small footprint before these changes, so I'm skeptical. We'll see.
I also updated some of the tile building scripts to make it easier for me to develop.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/219)

Simplify tile configuration

---

src/stackdriver-nozzle/nozzle/log_sink.go
src/stackdriver-nozzle/nozzle/log_sink_test.go

The message field in the logMessage payload was being duplicated into the payload.message field where Stackdriver is expecting to find it. There is no reason to have this information duplicated. It increases storage costs and is confusing for people to see the same information twice in search results.
I wrote this pull request to satisfy issue [#209](https://github.com/cloudfoundry-community/stackdriver-tools/issues/209)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/211)

Remove the duplication of the log message

---

ci/tasks/build-bosh-release.yml
ci/tasks/build-tile.yml
scripts/Dockerfile

These TODOs were to update the docker image m0pt0pmatt/tile-generator
to cfplatformeng/tile-generator. This has been done, but the TODOs were
left behind.

Remove old TODOs

---

Makefile
examples/cf-stackdriver-example/main.go
src/stackdriver-nozzle/app/builder.go
src/stackdriver-nozzle/app/runner.go
src/stackdriver-nozzle/cloudfoundry/app_info_repository.go
src/stackdriver-nozzle/cloudfoundry/firehose.go
src/stackdriver-nozzle/cloudfoundry/rlp_reader.go
src/stackdriver-nozzle/config/config.go
src/stackdriver-nozzle/messages/log.go
src/stackdriver-nozzle/messages/metric.go
src/stackdriver-nozzle/metricspipeline/buffer.go
src/stackdriver-nozzle/nozzle/filter_sink.go
src/stackdriver-nozzle/nozzle/label_maker.go
src/stackdriver-nozzle/nozzle/metric_sink.go
src/stackdriver-nozzle/nozzle/nozzle.go
src/stackdriver-nozzle/nozzle/parse_events.go
src/stackdriver-nozzle/nozzle/sink.go
src/stackdriver-nozzle/nozzle/unit_parser.go
src/stackdriver-nozzle/stackdriver/log_adapter.go
src/stackdriver-nozzle/stackdriver/metric_adapter.go
src/stackdriver-nozzle/stackdriver/metric_client.go
src/stackdriver-nozzle/version/version.go
src/stackdriver-spinner/cloudfoundry/emitter.go
src/stackdriver-spinner/cloudfoundry/emitter_test.go
src/stackdriver-spinner/fakes/probe.go
src/stackdriver-spinner/fakes/writers.go
src/stackdriver-spinner/main.go
src/stackdriver-spinner/session/session.go
src/stackdriver-spinner/stackdriver/logger.go
src/stackdriver-spinner/stackdriver/logging_probe.go

The purpose of this PR is to re-enable the `golint` linter as part of the CI process.
The reason it has been disabled is missing GoDoc.
This PR fixes GoDoc for:
* example app
* spinner
* nozzle
The `src/stackdriver-nozzle/mocks` packaged is excluded from linting for now. An Issue has been opened to explore better solutions: https://github.com/cloudfoundry-community/stackdriver-tools/issues/245
In some cases, variables which didn't need to be exported are no longer exported.
I also removed the example app's `/info` endpoint. I do not think it was being used by any health checks.

GoDoc fixes to re-enable the linter golint
