src/stackdriver-nozzle/main.go, src/stackdriver-nozzle/stackdriver/client.go
=> Adds configuration for batch size and duration

jobs/stackdriver-nozzle/templates/stackdriver-nozzle-ctl.erb
https://github.com/cloudfoundry-community/gcp-tools-release/pull/16/files?w=1
=> Use `pid_guard`, don't run in background

jobs/stackdriver-nozzle/spec, jobs/stackdriver-nozzle/templates/stackdriver-nozzle-ctl.erb
https://www.pivotaltracker.com/story/show/131195023
=> Add Bosh config for Firehose event types

packages/stackdriver-nozzle/packaging, src/stackdriver-nozzle/.envrc.template, src/stackdriver-nozzle/filter/filter.go, src/stackdriver-nozzle/main.go, src/stackdriver-nozzle/nozzle/nozzle.go, src/stackdriver-nozzle/stackdriver/client.go
Signed-off-by: Andres Medina <amedina@pivotal.io>
=> Use a normal GOPATH

ci/tasks/unit-tests.sh, src/stackdriver-nozzle/filter/filter_test.go, src/stackdriver-nozzle/heartbeat/heartbeat_test.go, src/stackdriver-nozzle/mocks/serializer.go, src/stackdriver-nozzle/nozzle/nozzle_test.go, src/stackdriver-nozzle/serializer/serializer_test.go
This change also fixes import pathes in several files.
=> Use new Go package layout in tests

ci/docker/Dockerfile, ci/docker/build-image.sh, ci/pipeline.yml, ci/tasks/build-candidate.yml, ci/tasks/deploy-candidate.yml, ci/tasks/unit-tests.yml
Signed-off-by: Matt Cholick <mcholick@pivotal.io>
=> Use our own docker file for builds.

ci/credentials.yml.tpl, ci/pipeline.yml, ci/tasks/deploy-candidate.sh, ci/tasks/deploy-candidate.yml, config/blobs.yml, packages/golang/packaging, packages/golang/spec
* Additional properties in credentials.yml.tpl (update your local copy)
=> Isolated integration deployment

ci/credentials.yml.tpl, ci/pipeline.yml
These changes to the pipeline are already loaded.
=> added slack hook to concourse to alert on CI failure

ci/pipeline-develop.yml, ci/tasks/deploy-candidate.sh, ci/tasks/deploy-candidate.yml
Spin up a CI pipeline for the develop branch.
This branch publishes to `gs://bosh-gcp/beta/develop-stackdriver-tools/stackdriver-tools-....tgz`
=> Pr develop ci

ci/pipeline.yml, tile.yml.erb
cb133d4 adds tile functionality. No change for BOSH users.
=> Release develop - tile only change

tile.yml.erb
=> Use credentials provided by ERT

tile.yml.erb
=> Promote Develop

src/stackdriver-nozzle/nozzle/metric_sink.go, src/stackdriver-nozzle/nozzle/metric_sink_test.go
=> nozzle/metric_sink: emit instanceIndex as a label

README.md, src/stackdriver-nozzle/README.md, tile.yml.erb
=> docs: Clarify project status/supported features

ci/docker-image/Dockerfile, ci/docker-image/system_tests/container_test.go
=> ci: add bosh2 to CI

jobs/stackdriver-nozzle/templates/stackdriver-nozzle-ctl.erb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/153)
=> Fix typo while setting LOGGING_BATCH_DURATION

tile.yml.erb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/159)
=> Remove colons from tile YAML. Fixes #155.

src/stackdriver-nozzle/metrics_pipeline/auto_culled_metrics_buffer_test.go
As discussed in #162.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/164)
=> Use context.Background in tests instead of context.TODO

src/stackdriver-spinner/main.go, src/stackdriver-spinner/stackdriver/logger.go
We've made the payload of the log summary structured. This will help in searching/slicing/dicing the logs.
Signed-off-by: James Wynne <jwynne@pivotal.io>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/170)
=> Change logger payload to json

scripts/build-custom-tile-docker.sh, scripts/build-docker-env.sh, scripts/custom-tile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/171)
=> Dockerfile and scripts to automate tile building.

src/stackdriver-nozzle/stackdriver/telemetry_sink.go, src/stackdriver-nozzle/stackdriver/telemetry_sink_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/176)
=> Telemetry sink should use foundation, not director.

jobs/stackdriver-nozzle/spec, jobs/stackdriver-nozzle/templates/event_filters.json.erb, jobs/stackdriver-nozzle/templates/stackdriver-nozzle-ctl.erb, src/stackdriver-nozzle/README.md, src/stackdriver-nozzle/app/app_suite_test.go, src/stackdriver-nozzle/app/builder.go, src/stackdriver-nozzle/app/builder_test.go, src/stackdriver-nozzle/config/config.go, src/stackdriver-nozzle/config/config_test.go, src/stackdriver-nozzle/nozzle/event_filter.go, src/stackdriver-nozzle/nozzle/event_filter_test.go, src/stackdriver-nozzle/nozzle/filter_sink.go, src/stackdriver-nozzle/nozzle/filter_sink_test.go, tile.yml.erb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/165)
=> Configurable filtering of firehose events.

src/stackdriver-nozzle/messages/metric.go
This makes sure that metric descriptors created implicitly by
Stackdriver have correct kind and value type.
Descriptors might be created implicitly after they are removed manually
using the Stackdriver API.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/180)
=> Set metric kind and value type when sending metric values

src/stackdriver-nozzle/stackdriver/telemetry_sink.go, src/stackdriver-nozzle/stackdriver/telemetry_sink_test.go, src/stackdriver-nozzle/telemetry/counters.go, src/stackdriver-nozzle/telemetry/reporter_test.go
I, uh... missed this crucial part from PR #160 :-(
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/184)
=> Propagate prefixes through to stackdriver.

ci/docker-image/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/187)
=> ci: add vim, bump bosh2

tile.yml.erb
Also: make the boolean a boolean, because why not?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/199)
=> MatchString is not anchored by default.

src/stackdriver-nozzle/Makefile, tile.yml.erb
To get [6760188db1a9158ac93d86ad2dc446075d0cd9f0](https://github.com/cloudfoundry-community/stackdriver-tools/commit/6760188db1a9158ac93d86ad2dc446075d0cd9f0) on the develop branch,
plus the tile changes @evandbrown made
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cloudfoundry-community/stackdriver-tools/214)
=> Merge master into develop

CHANGELOG.md, Makefile, tile.yml.erb
Merge the release changes to master, afterwards I'll create the Github release
=> Release v2.1.0
